name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [ '3.12']

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run flake8
        run: |
          flake8 app.py
